# Generated by Django 4.0.5 on 2022-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0003_alter_uppic_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppic',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/imgs'),
        ),
    ]
