# Generated by Django 4.0.5 on 2022-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0004_alter_uppic_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppic',
            name='photo',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
