# Generated by Django 4.0.5 on 2022-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0005_alter_uppic_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uppic',
            name='timedate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
