# Generated by Django 4.0.5 on 2022-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0006_uppic_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppic',
            name='photo',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
